core: &core
  adapter: postgresql  
  host: localhost
  encoding: unicode
  min_messages: warning
  pool: 5

development: &dev
  <<: *core
  database: shopify_api
  username: postgres
  password: postgres  

staging:
  <<: *dev
